### ISSUE TITLE
Hello, is it possible to make this work within tweetdeck.twitter.com?

### ISSUE THREAD

**Issue by UmbraVivens** [evazion/translate-pixiv-tags#29]
i find myself using tweetdeck more often than twitter itself and i LOVE this script, but it would be amazing if it worked in tweetdeck.

**Comment by 7nik** [comment]
I added it in the master branch, could you check it out?

**Comment by UmbraVivens** [comment]
wOOOOOOOOOOOOOW yes it is working! thank you very much. And just in case, could there be a part of documentation explaining how we can add compatibility for more websites (under the end user's responsibility of course)? Really thank you

**Comment by 7nik** [comment]
I'll discuss it.
If in short, you need to add in the header `@match` with your site, add function `initializeYourSiteName`, and call it in the function `initialize`.  The `initializeYourSiteName` may call `GM_addStyle` to add CSS and `findAndTranslate` to specify where and how translate tags. You can look at other initialing functions and realization of the `findAndTranslate` for more details.

**Comment by 7nik** [comment]
@UmbraVivens, I added to the wiki [an article](https://github.com/evazion/translate-pixiv-tags/wiki/How-to-add-support-of-one-more-site) about it.
