### ISSUE TITLE
Provide additional methods/info to exit settings menu

### ISSUE THREAD

**Issue by BrokenEagle** [evazion/translate-pixiv-tags#32]
To myself at least, it wasn't clear. I was looking for a cancel button, and also tried the escape key, both of which I'm used to from the jQuery dialog box as seen on Danbooru.

Some suggestions:
- Cancel button for exiting
- Escape key for exiting
  - Binding keys is normally pretty complicated, but the following extension makes it pretty easy (which is what Danbooru uses)
  - https://github.com/jeresig/jquery.hotkeys
  - https://raw.githubusercontent.com/jeresig/jquery.hotkeys/0.2.0/jquery.hotkeys.js
- Hint/help text to mention that focusing off the setting menu will cancel it
  - Either as hint text or as popup text on something like a question mark icon.

**Comment by 7nik** [comment]
I'm not glad to add library/plugin only for solving a quite trivial case.

**Comment by BrokenEagle** [comment]
Yeah, that's fine. It looks a bit cleaner, but I can also understand not wanting to add another library. As for myself and Danbooru, we use it a lot more often in our code so it makes sense to have it.
