### ISSUE TITLE
Settings menu doesn't open for some artist tags

### ISSUE THREAD

**Issue by BrokenEagle** [evazion/translate-pixiv-tags#33]
After some testing, it seems like this occurs when the same artist is selected a 2nd+ time from a different artist tag. The 1st will continue to work, but all others will not work. This does not affect different artists though. The following from example from Twitter demonstrates which ones have the issue.

![image](https://user-images.githubusercontent.com/21149935/64235139-9621b900-ceac-11e9-8246-505f9bff15ab.png)

Note that it's not because it's the 2nd that was rendered, but the 2nd popup that was initialized that was the issue. So if a user hovers over a particular artist tag, then only that artist tag will work for that artist on the entire page.

**Comment by 7nik** [comment]
I see. It happens because 2nd+ tooltips are cloned from the first and event handlers are not cloned.
