### ISSUE TITLE
Inclusion of Chinese tag translations

### ISSUE THREAD

**Issue by DonaldTsang** [evazion/translate-pixiv-tags#4]
For future reference https://www.pixiv.net/info.php?id=4623 has stated that they will include Chinese and English tags, and a related project https://github.com/zcyzcy88/TagTable/issues/2 has made an effort to do tag translation in their own language.

**Comment by DonaldTsang** [comment]
@zcyzcy88 if you could, please help this project out

**Comment by evazion** [comment]
See the README about how to add translations. This script will work with Chinese or Japanese tags, but new translations need to be added on Danbooru to be recognized by this script.

**Comment by DonaldTsang** [comment]
@evazion I would like to state that it is Pixiv who is doing the translation, so there might be a way to integrate this into translate-pixiv-tags
