### ISSUE TITLE
Incorrectly triggering on popup Twitter image

### ISSUE THREAD

**Issue by BrokenEagle** [evazion/translate-pixiv-tags#46]
When clicking an image on a tweet, I noticed that there were a whole bunch of TPT artist tags being added in the background. I outlined where they show up in red.

![image](https://user-images.githubusercontent.com/21149935/72467156-36f37f80-378f-11ea-93cc-8a9b2b11fb25.png)

The only link I was able to find nearby was the Twitter image link, so I imagine that it's doing an artist lookup on that and getting 10 bogus artists back. Regardless of the filtering code or whatever though, it shouldn't even be doing the query in the first place. It's a waste of both the client and Danbooru's resources.

**Comment by 7nik** [comment]
It's shitty Twitter's DOM. 
I committed a new filtering code, hope it will work longer than previous ones.
Later I'll try to make translating rules more specific.
