### ISSUE TITLE
script seems to have stopped working altogether

### ISSUE THREAD

**Issue by UmbraVivens** [evazion/translate-pixiv-tags#53]
![image](https://user-images.githubusercontent.com/54699529/90524893-76b68700-e123-11ea-8d61-bb72215b5794.png)
as seen in twitter
![image](https://user-images.githubusercontent.com/54699529/90526079-cfd2ea80-e124-11ea-9854-086ab202d9c2.png)
tweetdeck
![image](https://user-images.githubusercontent.com/54699529/90524939-846c0c80-e123-11ea-804b-1a87d31047e6.png)
pixiv
![image](https://user-images.githubusercontent.com/54699529/90525017-9fd71780-e123-11ea-9563-e5e0f460f78c.png)
pixiv tags are also back to "normal"

**Comment by 7nik** [comment]
Yeah, Danbooru API got a bit broken.
> Caused by danbooru/danbooru#4553
Will be fixed by danbooru/danbooru#4594

You can temporarily use this version https://github.com/BrokenEagle/translate-pixiv-tags/raw/4b1937dbbbdaa9d835664de320dc8b66ba8acbb2/translate-pixiv-tags.user.js

**Comment by BrokenEagle** [comment]
Yeah, this was fixed with https://github.com/danbooru/danbooru/pull/4594/commits/36fa8efcd52a3cbcc696c8d70910018a8d19814d and deployed yesterday so people can/should go back to the stable/mainline version.

**Comment by UmbraVivens** [comment]
looks like this is happening again

**Comment by 7nik** [comment]
@UmbraVivens there were some problems with Danbooru: https://twitter.com/danboorubot/status/1304696626481704962
