### ISSUE TITLE
Provide feedback when Danbooru is down

### ISSUE THREAD

**Issue by BrokenEagle** [evazion/translate-pixiv-tags#54]
This would keep people from reporting issues that aren't actually issues with the script, e.g. #53.

What PISAS does is that it puts `(Downbooru)`, `(Downbooru)`, or `(error)` when there is a problem with the network request to Downbooru.

https://github.com/BrokenEagle/userscripts/blob/bf6c641a691a08e7c0c7a7eda07604821de31376/Pixiv_Image_Searches_and_Stuff.user.js#L637-L658

In order to test the variety of network error responses, Danbooru provides the URL parameter `cause_error` which can be used, for example:

https://danbooru.donmai.us/posts.json?cause_error=404

I'd suggest testing at least the 502 response since that will respond with HTML from CloudFlare instead of Danbooru. Most other error codes seem to respond with JSON instead, so it would be good to test perhaps one or two others.

**Comment by UmbraVivens** [comment]
> Last night the script was working fine. Went to sleep and woke up, now it's no longer working, and the console log is reporting a whole slew of errors. Apparently it can't access Danbooru... even though I can open up the site's pages in the browser.

i started getting issues yesterday, specifically only one red artist URL appears per page, which happens on twitter feeds and pixiv posts, or none at all in the pixiv following feed. Danbooru still works perfectly fine.
if you proceed to a different page or interact with something that the script usually works with (like sections of sites that add more objects where artist URLs can appear), only the artist whose red link was previously parsed will persist (if it happens to be included in it), unless you reload

here's a screenshot of the console from my pixiv following feed
![image](https://user-images.githubusercontent.com/54699529/209790120-c2a2da72-a0ee-47f0-a6df-c57969eee704.png)

**Comment by 7nik** [comment]
@MarqFJA87 @UmbraVivens I fixed caching of failed requests and replaced endpoint with a faster one. Now there should be no timeouts that appeared recently.

**Comment by 7nik** [comment]
Now, there should appear a message at the top when requests fail
