### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by MarqFJA87** [evazion/translate-pixiv-tags#56]
The script abruptly stopped working completely on Twitter, Pixiv, DeviantArt, and possibly other sites. I'm using Chrome on Windows 10, fully updated.

**Comment by 7nik** [comment]
Can you disable Tampermonkey (on chrome://extensions/ ) and enable it back? 
If it fixes, then it is the external bug https://github.com/Tampermonkey/tampermonkey/issues/1215

**Comment by MarqFJA87** [comment]
I tried that, and it didn't fix it. For the record, I have already restarted Chrome just in case, and it did nothing.

**Comment by 7nik** [comment]
Well, are there any related errors in the console? And does TM say the userscript is running?

**Comment by MarqFJA87** [comment]
Yes, TM says the userscript is running. When I open the console, however, I find that there are several errors pertaining to userscripts that seem to be trying to access Danbooru, with the Issues sidebar noting that "Content Security Policy of your site blocks the use of 'eval' in JavaScript".

**Comment by 7nik** [comment]
Sounds as it cannot connect to Danbooru or, hm, Danbooru reject requests? Hard to say without details.
Are you able to visit Danbooru? And maybe try [TM Beta](https://chrome.google.com/webstore/detail/tampermonkey-beta/gcalenpjmijncebpfijmoaglllgpjagf)?

**Comment by MarqFJA87** [comment]
Huh. I just realized that I'm indeed unable to access Danbooru right now without the use of Psiphon as a VPN, even though I've been able to for what seems like forever now. No "this page was blocked" message page like I'd see when I try to access pages that have been actively blocked by my country's censors, though.

**Comment by 7nik** [comment]
So, there is nothing to do with TM beta.
You just need to fix your access to Danbooru.
You can ask for help at their Discord https://discord.gg/VfJf34HC

**Comment by MarqFJA87** [comment]
> So, there is nothing to do with TM beta.
> You just need to fix your access to Danbooru.
> You can ask for help at their Discord https://discord.gg/VfJf34HC

Danbooru became accessible again about 36 hours ago, and with it the script has started working again; consulting with the people at Danbooru presented the possible explanation that the issue is with Cloudflare suffering an outage, since it provides the site's security certificate.

**Comment by UmbraVivens** [comment]
i'm having problems with the script too, except i have absolutely no issue with access to danbooru.
it only works "by random bursts". like i can be on tweetdeck and as i scroll the script's features appear in like a couple tweets and no more, or see an account at twitter.com and the script features appear, until i refresh... but it seems to only work 100% in saucenao results page.
i just tried the "turning TM off and on" but didn't work

**Comment by 7nik** [comment]
Are there any suspicious errors in the console?

**Comment by UmbraVivens** [comment]
didn't check before but yes, this is what the console on pixiv said
![image](https://user-images.githubusercontent.com/54699529/121103414-bfbff080-c7b4-11eb-828f-6b33b446b391.png)
![image](https://user-images.githubusercontent.com/54699529/121103600-20e7c400-c7b5-11eb-997a-bd0eea69ea57.png)

the second screenshot looks different somehow, but i took it when i refreshed after taking the first one

**Comment by 7nik** [comment]
Well, likely it means that Danbooru is too busy so you don't get a response.
I'll try to look deeper later.
