### ISSUE TITLE
the danbooru artist red link stopped appearing in pixiv's user profile page

### ISSUE THREAD

**Issue by UmbraVivens** [evazion/translate-pixiv-tags#57]
like this here
![image](https://user-images.githubusercontent.com/54699529/140465424-e89c8d67-9b71-4a26-bee6-7033e33ec10f.png)

but it still works when you enter a gallery post
![image](https://user-images.githubusercontent.com/54699529/140465486-64cadf71-386e-4cb1-844c-a398d17d1298.png)

**Comment by 7nik** [comment]
Oh, I've forgotten how to update it right.
Just update userscript or it will do it automatically during a day.
