### ISSUE TITLE
Suggested feature: option to turn off Bookmark Tagging Suggestions

### ISSUE THREAD

**Issue by tychoid** [evazion/translate-pixiv-tags#58]
Love the script!  Wish I could turn off just one thing though; the tag suggestions under "Your bookmark tags" when you are trying to quick-select most used tags under a bookmark.  For me, it really makes the tags a little too busy to navigate comfortably.  Thanks! 
![Screenshot 2022-01-26 151531](https://user-images.githubusercontent.com/28597551/151256112-07997996-83f1-4c1d-9e7d-63a3e7a59cb2.png)

**Comment by 7nik** [comment]
Sorry for the delay.
How could you run into this issue? The bookmark tags are loaded dynamically, so they shouldn't get translated (unless you maybe have dozens of userscript, which makes TPT run really late). Also, AFAIK, this page was replaced with the new UI.
