### ISSUE TITLE
update /artist_urls definition to use search[url_matches]=

### ISSUE THREAD

**Issue by bipface** [evazion/translate-pixiv-tags#70]
with [issue 5445](https://github.com/danbooru/danbooru/issues/5445) resolved the slow and troublesome `url_lower_array` search operation can be replaced with `url_matches`,
however with the changes only deployed to betabooru currently, we may want to wait until they reach production before updating the userscript.

the new endpoint definition may look something like the following:

```js
    url: {
        url: "/artist_urls",
        ...
        params (urlList) {
            return {
                search: {
                    url_matches: urlList.map(s => s.replaceAll(/\s+/g, '*')).join(' '),
```

also keeping in mind [issue 5447](https://github.com/danbooru/danbooru/issues/5447)

**Comment by 7nik** [comment]
I switched the endpoint to a faster one two months ago in https://github.com/evazion/translate-pixiv-tags/commit/b9a6dc77d699eb49fca45bf7ac595ebb87a360e9

About the space and asterisk - I doubt that supported sites allow them in usernames.
