### ISSUE TITLE
The script fails at pixiv profile page for artist with 0 followers

### ISSUE THREAD

**Issue by 7nik** [evazion/translate-pixiv-tags#8]
If a pixiv artist has 0 followers then there is no `a._13OcQAQ` element and the script can't add artist translation.
Example: https://www.pixiv.net/member.php?id=13167207 a.k.a. [berryverrine](https://danbooru.donmai.us/artists/137583) on the Danbooru.

**Comment by evazion** [comment]
Fixed by switching to use the profile image element:

![image](https://user-images.githubusercontent.com/8430473/51077036-592b5c80-1666-11e9-9401-c03851517b6a.png)

There's less space here, though, so sometimes long names have to linewrap.

**Comment by 7nik** [comment]
Why not add the link after user name?
`    asyncAddTranslatedArtists("._2VLnXNk", "._2VLnXNk", ()=>window.location.href.match(/[?&]id=(\d+)/)[1]);`
And a little of css for better look
`#ex-pixiv ._2qMhDQk {
    flex-direction: column;
    align-items: flex-start;
}
`
![image](https://user-images.githubusercontent.com/29704098/51086737-f06dde00-1752-11e9-9dd2-eaaae08e594a.png)
