### ISSUE TITLE
Translate Pixiv Tags doesn't show the artist tag on Fantia

### ISSUE THREAD

**Issue by TheF3nt0n** [evazion/translate-pixiv-tags#92]
The artist tag cannot be seen on Fantia anymore, but the other tags still appear.
![image](https://github.com/evazion/translate-pixiv-tags/assets/80976950/8adc9011-ceb8-4c8f-9b0d-c6c9098b846e)

The other tags still show up though.
![image](https://github.com/evazion/translate-pixiv-tags/assets/80976950/a9295ecc-eeca-4970-b31a-620596a10b06)

**Comment by 7nik** [comment]
Matching Fantia urls on Danbooru seems broken.
