### ISSUE TITLE
Add a way in the artist popup to differentiate posts that are `ai-generated` or `ai-assisted`

### ISSUE THREAD

**Issue by BrokenEagle** [evazion/translate-pixiv-tags#96]
This would help users identify artists that use AI entirely, or off and on, so as to better judge whether a potential artwork from said artist should be uploaded or not. Perhaps keep the top and left borders black for deleted, and use the lower and right borders for either AI generated or AI assisted? Or just replace the black border entirely?

As an alternative to borders, perhaps adding an extra row beneath the thumbnails (alongside the size, type, dimensions, and source) that is kept blank normally for most posts, but when it finds an AI artwork, it'd add either "AI-generated" or "AI-assisted".

**Comment by 7nik** [comment]
AFAIK, deleted AI posts on Danbooru aren't marked. It will be hard for users to guess what the new border colour means.
Another alternative is an overlay icon in the top right corner, like the sound one.

**Comment by BrokenEagle** [comment]
Yes, that's true. They are highlighted in the modqueue with a red background,

https://github.com/danbooru/danbooru/blob/061337895bf287eeac780490322c2de7b5c882b8/config/danbooru_default_config.rb#L621
https://github.com/danbooru/danbooru/blob/061337895bf287eeac780490322c2de7b5c882b8/app/views/modqueue/_post_preview_footer.html.erb#L46

which wouldn't be familiar to most users who only have access to the post/INDEX.

An overlay icon would be another solution, but it would probably require something additional then, like hover text, i.e. `title="AI-assisted"` or `title="AI-generated"`, just as a way to hint the user as to what they mean.

**Comment by 7nik** [comment]
I was thinking about something like bold red AI for `ai-generated` and yellow/orange +AI for `ai-assisted` with some hints like `title`.

**Comment by BrokenEagle** [comment]
Yeah, that would work. You should check out how Danbooru does the animation icon (duration and audio icon if it has sound), which is slightly rounded with a dark slightly transparent background which gives the text/icon a good contrast.

```css
background: rgba(0 0 0 / 70%);
border-radius: .25rem;
```
